locale: "en-kr"
title: 데린이 블로그
author:
  name: "JeonghyunGan"
  bio: "awesome guy"
  location: Seoul, Korea

description: 데린이쟝의 블로그
show_excerpts: false # set to true to show excerpts on the homepage
url: "https://JeonghyunGan.github.io"
repository: JeonghyunGan/JeonghyunGan.github.io
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
markdown: kramdown
use_math: true
sidebar:
  -title: "데리니쟝"

minima:
  date_format: "%b %-d, %Y"
lsi: false
excerpt_separator: "\n\n"
incremental: false
future: true

  # generate social links in footer
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
